baseURL = "https://alpinelinux.org/"
languageCode = "en-us"
title = "Alpine Linux"
theme = "ananke"
#themesDir = "../.."

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[params]
  favicon = ""
  site_logo = "/images/alpinelinux-logo.svg"
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""

  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/banner.jpg"
  recent_posts_number = 9


[menu]
 
   [[menu.main]]
     identifier = "home"
     name = "Home"
     url = "/"
     weight = -110
 
   [[menu.main]]
     identifier = "download"
     name = "Downloads"
     url = "/downloads/"
     weight = -100
 
   [[menu.main]]
     identifier = "about"
     name = "About"
     url = "/about/"
     weight = -90

   [[menu.main]]
     identifier = "community"
     name = "Community"
     url = "/community/"
     weight = -80

   [[menu.main]]
     identifier = "ponsors"
     name = "Sponsors"
     url = "/sponsors/"
     weight = -70


